apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow:latest
        command: ["mlflow"]
        args:
        - server
        - --backend-store-uri
        - postgresql://mlflow:mlflowpass@postgres-postgresql:5432/mlflowdb
        - --default-artifact-root
        - s3://mlflow
        - --host
        - 0.0.0.0
        - --allowed-hosts
        - "*"
        env:
        - name: AWS_ACCESS_KEY_ID
          value: admin
        - name: AWS_SECRET_ACCESS_KEY
          value: admin12345
        - name: MLFLOW_S3_ENDPOINT_URL
          value: http://minio:9000